apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-home-starter-front
  namespace: homestarter-ns
data:
  runtime-env.js: |
    // 런타임 환경 설정 - 배포 시 환경별로 변경 가능
    window.__runtime_config__ = {
      USER_HOST: "http://homestarter-api.172.30.1.205.nip.io/users",
      ASSET_HOST: "http://homestarter-api.172.30.1.205.nip.io/api/v1/assets",
      HOUSING_HOST: "http://homestarter-api.172.30.1.205.nip.io/housing",
      LOAN_HOST: "http://homestarter-api.172.30.1.205.nip.io/api/v1/loans",
      LOAN_HOST: "http://homestarter-api.172.30.1.205.nip.io/api/v1/admin/loans",
      CALCULATOR_HOST: "http://homestarter-api.172.30.1.205.nip.io/calculator",
      ROADMAP_HOST: "http://homestarter-api.172.30.1.205.nip.io/roadmaps"
    };
