apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-starter-front
  namespace: homestarter-ns
spec:
  ingressClassName: nginx
  rules:
    - host: homestarter.172.30.1.205.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-starter-front
                port:
                  number: 8080
