apiVersion: v1
kind: Service
metadata:
  name: home-starter-front
  namespace: homestarter-ns
spec:
  type: ClusterIP
  selector:
    app: home-starter-front
  ports:
    - port: 8080
      targetPort: 8080
